version: '3.8'

services:
  excusemyfrench:
    build: .
    container_name: excusemyfrench
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      - ./models:/app/models
      - ./config:/app/config
      # Mount scripts for development
      - ./scripts:/app/scripts:ro
    env_file:
      - config/.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: /bin/bash
    stdin_open: true
    tty: true

  comfyui:
    image: ghcr.io/comfyanonymous/comfyui:latest
    container_name: comfyui
    runtime: nvidia
    ports:
      - "8188:8188"
    volumes:
      - ./models:/app/models
      - ./comfyui/workflows:/app/workflows
      - ./data/images:/app/output
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/workflows
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=change_me_please
      - WEBHOOK_URL=http://localhost:5678/
    restart: unless-stopped

volumes:
  n8n_data:
